version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: sudo npm add -g pnpm
      - run: pnpm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: pnpm run build
      - run: pnpm run lint
