version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: 
        - name: Install pnpm
        - command: sudo npm add -g pnpm
      
      - run:
        - name: Install packages
        - command: pnpm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
        - name: Typescript build
        - command: pnpm run build
      
      - run:
        - name: Lint
        - command: pnpm run lint
